# Defaults for objectnav.sim.NavmeshConfig

# --- Navmesh parameters ---
include_static_objects: true
cell_size: 0.05
cell_height: 0.1
filter_low_hanging_obstacles: true
filter_ledge_spans: true
filter_walkable_low_height_spans: true

# --- Agent geometry ---
agent_height: 1.5
agent_radius: 0.2
agent_max_climb: 0.2
agent_max_slope: 45.0
